### ISSUE TITLE
fix temperature reading

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/MATS-L1-processing#30] opened 2022-09-06 13:02 UTC
At the moment the temperature is set from what is measured at the UV2 channel ,             CCDitem["temperature"] = HTR8A  # , 
see get_temperature.py. This should be made in a better way.

**Comment by skymandr** [comment] 2023-07-07 14:21
Duplicate of #65

**Closed by skymandr** 2023-07-07 14:21 UTC
Labels: duplicate
