### ISSUE TITLE
Problems generating a CCDitem from the parquette files

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/MATS-L1-processing#75] opened 2022-12-12 19:40 UTC
# 🐛 Description
I have problems generating a CCDitem from the parquette files

# 🔢 To reproduce

``` python 
read_ccd_items_in_interval(start_date, end_date, "ops-payload-level1a-v0.2", s3)
```

# ✌🏽 Expected behaviour

no crash

# 💻 Traceback

``` python
'ImageName'
File "/home/olemar/Projects/Universitetet/MATS/MATS-L1-processing/src/mats_l1_processing/read_parquet_functions.py", line 86, in add_ccd_item_attributes
Image.open(BytesIO(image_data)),

During handling of the above exception, another exception occurred:

The above exception was the direct cause of the following exception:

File "/home/olemar/Projects/Universitetet/MATS/MATS-L1-processing/src/mats_l1_processing/read_parquet_functions.py", line 89, in add_ccd_item_attributes
image_name = ccd_data["ImageName"][ind]
File "/home/olemar/Projects/Universitetet/MATS/MATS-L1-processing/src/mats_l1_processing/read_parquet_functions.py", line 147, in dataframe_to_ccd_items
add_ccd_item_attributes(ccd_data)
File "/home/olemar/Projects/Universitetet/MATS/MATS-L1-processing/src/mats_l1_processing/read_parquet_functions.py", line 206, in read_ccd_items_in_interval
return dataframe_to_ccd_items(
File "/home/olemar/Projects/Universitetet/MATS/MATS-utility-functions/src/rawdata/read_data.py", line 34, in read_MATS_data
df = read_ccd_items_in_interval(start_date,end_date,"ops-payload-level1a-v0.2",s3)
File "/home/olemar/Projects/Universitetet/MATS/MATS-utility-functions/tests/test_raw_data.py", line 17, in test_read_MATS_data
CCDitems = read_data.read_MATS_data(start_time,stop_time)
File "/home/olemar/Projects/Universitetet/MATS/MATS-utility-functions/tests/test_raw_data.py", line 22, in
test_read_MATS_data()
```

**Comment by skymandr** [comment] 2022-12-12 21:01
@OleMartinChristensen  I can't reproduce the issue, but I'll have another look tomorrow. Meanwhile, some of the error output seems to be missing (above `'ImageName'`). Could you amend the output above with the missing pieces?

**Comment by OleMartinChristensen** [comment] 2022-12-13 12:00
start_time = DT.datetime(2022,12,4,0,0,0,tzinfo=DT.timezone.utc)
    stop_time = DT.datetime(2022,12,5,0,0,0,tzinfo=DT.timezone.utc)
    df = read_data.read_MATS_data(start_time,stop_time)

**Comment by OleMartinChristensen** [comment] 2022-12-13 12:02
images: List[Optional[Any]] = []
    for ind, image_data in enumerate(ccd_data["ImageData"]):
        try:
            images.append(np.float64(cast(
                SupportsFloat,
                Image.open(BytesIO(image_data)),
            )))
        except Exception as err:
            image_name = ccd_data["ImageName"][ind]  <--- Fails here
            logging.warning(
                f"could not prepare image {image_name} for calibration. "
                f"Setting image data to `None`. (Error: {err})"
            )
            images.append(None)
    ccd_data["IMAGE"] = images

**Comment by skymandr** [comment] 2022-12-13 12:21
> I think there is some issue with add_ccd_item_attributes not beeing consistent in the use of old or new data names ccd_data["ImageName"] is new name yet further down ccd_data['EXP Nanoseconds'] us used which is old name. I suggest using only new names in this function. We can instead make and inverse rename_ccd_item_attributes if old format is needed. @skymandr @e-larsson

Well spotted, @OleMartinChristensen! Fixed in my branch. Tell me if you think this is urgent enough that I should make a patch PR before I'm done with what I'm doing.

**Comment by OleMartinChristensen** [comment] 2022-12-13 12:24
No stress, I fixed the small issues in my branch now. Please just list me as reviewer when you do the pull request then I can see if its solved the way I want it ;)

**Closed** 2022-12-13 15:25 UTC
Labels: bug
